### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by fastestdevalive** [scholtzm/vapor#8]
When using vapor in a production environment with electron. I am getting this error when trying to do 
require('vapor').

**Comment by scholtzm** [comment]
Looks like the issue title is incomplete?

**Comment by gaurav414u** [comment]
Uncaught Error: ENOENT: no such file or directory, uv_chdir
Error: ENOENT: no such file or directory, uv_chdir
    at %appdir%\app-2.0.9\resources\app.asar\node_modules\steam\node_modules\steam-resources\steam_language_parser\index.js:8:9
    at Object.<anonymous> (%appdir%\app-2.0.9\resources\app.asar\node_modules\steam\node_modules\steam-resources\steam_language_parser\index.js:25:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at %appdir%\app-2.0.9\resources\app.asar\node_modules\steam\node_modules\steam-resources\index.js:81:1

**Comment by fastestdevalive** [comment]
```
Uncaught Error: ENOENT: no such file or directory, uv_chdir
Error: ENOENT: no such file or directory, uv_chdir
at %appdir%\app-2.0.9\resources\app.asar\node_modules\steam\node_modules\steam-resources\steam_language_parser\index.js:8:9
at Object. (%appdir%\app-2.0.9\resources\app.asar\node_modules\steam\node_modules\steam-resources\steam_language_parser\index.js:25:2)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at %appdir%\app-2.0.9\resources\app.asar\node_modules\steam\node_modules\steam-resources\index.js:81:1
```

**Comment by scholtzm** [comment]
That has nothing to do with Vapor. You cannot call `chdir` in `asar` archive. See their docs.

I have solved this in my [Punk](https://github.com/scholtzm/punk) project by providing a [custom monkey patch](https://github.com/scholtzm/punk/blob/master/src/utils/monkey-patch.js).

**Comment by fastestdevalive** [comment]
Thanks @scholtzm !
